services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: bebetobet-backend-app
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    volumes:
      - .:/var/www/html
    networks:
      - bebetobet-backend

  nginx:
    image: nginx:1.24.0-alpine
    container_name: bebetobet-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    networks:
      - bebetobet-network-external
      - bebetobet-backend
    depends_on:
      - app

networks:
  bebetobet-network-external:
    internal: false
  bebetobet-backend:
    internal: true
